// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxsdhctxkuqukjvmhuvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4c2RoY3R4a3VxdWtqdm1odXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2MzY5MjIsImV4cCI6MjA1MzIxMjkyMn0.y8VomIyU9-DPsYp-aDQFlwcV74FXo9KmdS3GexFxyk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);